from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CreateNodeRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, parent_path=None, node_type=None, node_name=None):  # noqa: E501
        """CreateNodeRequest - a model defined in OpenAPI

        :param parent_path: The parent_path of this CreateNodeRequest.  # noqa: E501
        :type parent_path: str
        :param node_type: The node_type of this CreateNodeRequest.  # noqa: E501
        :type node_type: str
        :param node_name: The node_name of this CreateNodeRequest.  # noqa: E501
        :type node_name: str
        """
        self.openapi_types = {
            'parent_path': str,
            'node_type': str,
            'node_name': str
        }

        self.attribute_map = {
            'parent_path': 'parentPath',
            'node_type': 'nodeType',
            'node_name': 'nodeName'
        }

        self._parent_path = parent_path
        self._node_type = node_type
        self._node_name = node_name

    @classmethod
    def from_dict(cls, dikt) -> 'CreateNodeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The create_node_request of this CreateNodeRequest.  # noqa: E501
        :rtype: CreateNodeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def parent_path(self) -> str:
        """Gets the parent_path of this CreateNodeRequest.

        Path to the parent node (e.g., /project1)  # noqa: E501

        :return: The parent_path of this CreateNodeRequest.
        :rtype: str
        """
        return self._parent_path

    @parent_path.setter
    def parent_path(self, parent_path: str):
        """Sets the parent_path of this CreateNodeRequest.

        Path to the parent node (e.g., /project1)  # noqa: E501

        :param parent_path: The parent_path of this CreateNodeRequest.
        :type parent_path: str
        """
        if parent_path is None:
            raise ValueError("Invalid value for `parent_path`, must not be `None`")  # noqa: E501

        self._parent_path = parent_path

    @property
    def node_type(self) -> str:
        """Gets the node_type of this CreateNodeRequest.

        Type of the node to create (e.g., textTop)  # noqa: E501

        :return: The node_type of this CreateNodeRequest.
        :rtype: str
        """
        return self._node_type

    @node_type.setter
    def node_type(self, node_type: str):
        """Sets the node_type of this CreateNodeRequest.

        Type of the node to create (e.g., textTop)  # noqa: E501

        :param node_type: The node_type of this CreateNodeRequest.
        :type node_type: str
        """
        if node_type is None:
            raise ValueError("Invalid value for `node_type`, must not be `None`")  # noqa: E501

        self._node_type = node_type

    @property
    def node_name(self) -> str:
        """Gets the node_name of this CreateNodeRequest.

        Name of the new node (optional)  # noqa: E501

        :return: The node_name of this CreateNodeRequest.
        :rtype: str
        """
        return self._node_name

    @node_name.setter
    def node_name(self, node_name: str):
        """Sets the node_name of this CreateNodeRequest.

        Name of the new node (optional)  # noqa: E501

        :param node_name: The node_name of this CreateNodeRequest.
        :type node_name: str
        """

        self._node_name = node_name
