from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.td_node import TdNode
from openapi_server import util

from openapi_server.models.td_node import TdNode  # noqa: E501

class CreateNode200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):  # noqa: E501
        """CreateNode200ResponseData - a model defined in OpenAPI

        :param result: The result of this CreateNode200ResponseData.  # noqa: E501
        :type result: TdNode
        """
        self.openapi_types = {
            'result': TdNode
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'CreateNode200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The create_node_200_response_data of this CreateNode200ResponseData.  # noqa: E501
        :rtype: CreateNode200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TdNode:
        """Gets the result of this CreateNode200ResponseData.


        :return: The result of this CreateNode200ResponseData.
        :rtype: TdNode
        """
        return self._result

    @result.setter
    def result(self, result: TdNode):
        """Sets the result of this CreateNode200ResponseData.


        :param result: The result of this CreateNode200ResponseData.
        :type result: TdNode
        """

        self._result = result
