from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.td_node import TdNode
from openapi_server import util

from openapi_server.models.td_node import TdNode  # noqa: E501

class DeleteNode200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, deleted=None, node=None):  # noqa: E501
        """DeleteNode200ResponseData - a model defined in OpenAPI

        :param deleted: The deleted of this DeleteNode200ResponseData.  # noqa: E501
        :type deleted: bool
        :param node: The node of this DeleteNode200ResponseData.  # noqa: E501
        :type node: TdNode
        """
        self.openapi_types = {
            'deleted': bool,
            'node': TdNode
        }

        self.attribute_map = {
            'deleted': 'deleted',
            'node': 'node'
        }

        self._deleted = deleted
        self._node = node

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteNode200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The delete_node_200_response_data of this DeleteNode200ResponseData.  # noqa: E501
        :rtype: DeleteNode200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deleted(self) -> bool:
        """Gets the deleted of this DeleteNode200ResponseData.

        Whether the node was successfully deleted  # noqa: E501

        :return: The deleted of this DeleteNode200ResponseData.
        :rtype: bool
        """
        return self._deleted

    @deleted.setter
    def deleted(self, deleted: bool):
        """Sets the deleted of this DeleteNode200ResponseData.

        Whether the node was successfully deleted  # noqa: E501

        :param deleted: The deleted of this DeleteNode200ResponseData.
        :type deleted: bool
        """

        self._deleted = deleted

    @property
    def node(self) -> TdNode:
        """Gets the node of this DeleteNode200ResponseData.


        :return: The node of this DeleteNode200ResponseData.
        :rtype: TdNode
        """
        return self._node

    @node.setter
    def node(self, node: TdNode):
        """Sets the node of this DeleteNode200ResponseData.


        :param node: The node of this DeleteNode200ResponseData.
        :type node: TdNode
        """

        self._node = node
