from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ExecNodeMethod200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):  # noqa: E501
        """ExecNodeMethod200ResponseData - a model defined in OpenAPI

        :param result: The result of this ExecNodeMethod200ResponseData.  # noqa: E501
        :type result: object
        """
        self.openapi_types = {
            'result': object
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'ExecNodeMethod200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The exec_node_method_200_response_data of this ExecNodeMethod200ResponseData.  # noqa: E501
        :rtype: ExecNodeMethod200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> object:
        """Gets the result of this ExecNodeMethod200ResponseData.

        Result of the method call. Can be any type (equivalent to unknown in TypeScript).  # noqa: E501

        :return: The result of this ExecNodeMethod200ResponseData.
        :rtype: object
        """
        return self._result

    @result.setter
    def result(self, result: object):
        """Sets the result of this ExecNodeMethod200ResponseData.

        Result of the method call. Can be any type (equivalent to unknown in TypeScript).  # noqa: E501

        :param result: The result of this ExecNodeMethod200ResponseData.
        :type result: object
        """
        if result is None:
            raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501

        self._result = result
