from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.exec_node_method_request_args_inner import ExecNodeMethodRequestArgsInner
from openapi_server import util

from openapi_server.models.exec_node_method_request_args_inner import ExecNodeMethodRequestArgsInner  # noqa: E501

class ExecNodeMethodRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, node_path=None, method=None, args=None, kwargs=None):  # noqa: E501
        """ExecNodeMethodRequest - a model defined in OpenAPI

        :param node_path: The node_path of this ExecNodeMethodRequest.  # noqa: E501
        :type node_path: str
        :param method: The method of this ExecNodeMethodRequest.  # noqa: E501
        :type method: str
        :param args: The args of this ExecNodeMethodRequest.  # noqa: E501
        :type args: List[ExecNodeMethodRequestArgsInner]
        :param kwargs: The kwargs of this ExecNodeMethodRequest.  # noqa: E501
        :type kwargs: Dict[str, object]
        """
        self.openapi_types = {
            'node_path': str,
            'method': str,
            'args': List[ExecNodeMethodRequestArgsInner],
            'kwargs': Dict[str, object]
        }

        self.attribute_map = {
            'node_path': 'nodePath',
            'method': 'method',
            'args': 'args',
            'kwargs': 'kwargs'
        }

        self._node_path = node_path
        self._method = method
        self._args = args
        self._kwargs = kwargs

    @classmethod
    def from_dict(cls, dikt) -> 'ExecNodeMethodRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The exec_node_method_request of this ExecNodeMethodRequest.  # noqa: E501
        :rtype: ExecNodeMethodRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node_path(self) -> str:
        """Gets the node_path of this ExecNodeMethodRequest.

        Path to the node (e.g., /project1/null1)  # noqa: E501

        :return: The node_path of this ExecNodeMethodRequest.
        :rtype: str
        """
        return self._node_path

    @node_path.setter
    def node_path(self, node_path: str):
        """Sets the node_path of this ExecNodeMethodRequest.

        Path to the node (e.g., /project1/null1)  # noqa: E501

        :param node_path: The node_path of this ExecNodeMethodRequest.
        :type node_path: str
        """
        if node_path is None:
            raise ValueError("Invalid value for `node_path`, must not be `None`")  # noqa: E501

        self._node_path = node_path

    @property
    def method(self) -> str:
        """Gets the method of this ExecNodeMethodRequest.

        Name of the method to call  # noqa: E501

        :return: The method of this ExecNodeMethodRequest.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method: str):
        """Sets the method of this ExecNodeMethodRequest.

        Name of the method to call  # noqa: E501

        :param method: The method of this ExecNodeMethodRequest.
        :type method: str
        """
        if method is None:
            raise ValueError("Invalid value for `method`, must not be `None`")  # noqa: E501

        self._method = method

    @property
    def args(self) -> List[ExecNodeMethodRequestArgsInner]:
        """Gets the args of this ExecNodeMethodRequest.

        List of arguments for the method call  # noqa: E501

        :return: The args of this ExecNodeMethodRequest.
        :rtype: List[ExecNodeMethodRequestArgsInner]
        """
        return self._args

    @args.setter
    def args(self, args: List[ExecNodeMethodRequestArgsInner]):
        """Sets the args of this ExecNodeMethodRequest.

        List of arguments for the method call  # noqa: E501

        :param args: The args of this ExecNodeMethodRequest.
        :type args: List[ExecNodeMethodRequestArgsInner]
        """

        self._args = args

    @property
    def kwargs(self) -> Dict[str, object]:
        """Gets the kwargs of this ExecNodeMethodRequest.

        Keyword arguments for the method call  # noqa: E501

        :return: The kwargs of this ExecNodeMethodRequest.
        :rtype: Dict[str, object]
        """
        return self._kwargs

    @kwargs.setter
    def kwargs(self, kwargs: Dict[str, object]):
        """Sets the kwargs of this ExecNodeMethodRequest.

        Keyword arguments for the method call  # noqa: E501

        :param kwargs: The kwargs of this ExecNodeMethodRequest.
        :type kwargs: Dict[str, object]
        """

        self._kwargs = kwargs
