from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.exec_python_script200_response_data_result import ExecPythonScript200ResponseDataResult
from openapi_server import util

from openapi_server.models.exec_python_script200_response_data_result import ExecPythonScript200ResponseDataResult  # noqa: E501

class ExecPythonScript200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):  # noqa: E501
        """ExecPythonScript200ResponseData - a model defined in OpenAPI

        :param result: The result of this ExecPythonScript200ResponseData.  # noqa: E501
        :type result: ExecPythonScript200ResponseDataResult
        """
        self.openapi_types = {
            'result': ExecPythonScript200ResponseDataResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'ExecPythonScript200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The exec_python_script_200_response_data of this ExecPythonScript200ResponseData.  # noqa: E501
        :rtype: ExecPythonScript200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> ExecPythonScript200ResponseDataResult:
        """Gets the result of this ExecPythonScript200ResponseData.


        :return: The result of this ExecPythonScript200ResponseData.
        :rtype: ExecPythonScript200ResponseDataResult
        """
        return self._result

    @result.setter
    def result(self, result: ExecPythonScript200ResponseDataResult):
        """Sets the result of this ExecPythonScript200ResponseData.


        :param result: The result of this ExecPythonScript200ResponseData.
        :type result: ExecPythonScript200ResponseDataResult
        """
        if result is None:
            raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501

        self._result = result
