from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.td_python_class_info import TdPythonClassInfo
from openapi_server import util

from openapi_server.models.td_python_class_info import TdPythonClassInfo  # noqa: E501

class GetTdPythonClasses200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, classes=None):  # noqa: E501
        """GetTdPythonClasses200ResponseData - a model defined in OpenAPI

        :param classes: The classes of this GetTdPythonClasses200ResponseData.  # noqa: E501
        :type classes: List[TdPythonClassInfo]
        """
        self.openapi_types = {
            'classes': List[TdPythonClassInfo]
        }

        self.attribute_map = {
            'classes': 'classes'
        }

        self._classes = classes

    @classmethod
    def from_dict(cls, dikt) -> 'GetTdPythonClasses200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_td_python_classes_200_response_data of this GetTdPythonClasses200ResponseData.  # noqa: E501
        :rtype: GetTdPythonClasses200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def classes(self) -> List[TdPythonClassInfo]:
        """Gets the classes of this GetTdPythonClasses200ResponseData.


        :return: The classes of this GetTdPythonClasses200ResponseData.
        :rtype: List[TdPythonClassInfo]
        """
        return self._classes

    @classes.setter
    def classes(self, classes: List[TdPythonClassInfo]):
        """Sets the classes of this GetTdPythonClasses200ResponseData.


        :param classes: The classes of this GetTdPythonClasses200ResponseData.
        :type classes: List[TdPythonClassInfo]
        """

        self._classes = classes
