from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.td_node import TdNode
from openapi_server import util

from openapi_server.models.td_node import TdNode  # noqa: E501

class GetNodes200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nodes=None):  # noqa: E501
        """GetNodes200ResponseData - a model defined in OpenAPI

        :param nodes: The nodes of this GetNodes200ResponseData.  # noqa: E501
        :type nodes: List[TdNode]
        """
        self.openapi_types = {
            'nodes': List[TdNode]
        }

        self.attribute_map = {
            'nodes': 'nodes'
        }

        self._nodes = nodes

    @classmethod
    def from_dict(cls, dikt) -> 'GetNodes200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_nodes_200_response_data of this GetNodes200ResponseData.  # noqa: E501
        :rtype: GetNodes200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nodes(self) -> List[TdNode]:
        """Gets the nodes of this GetNodes200ResponseData.

        Result of the execution  # noqa: E501

        :return: The nodes of this GetNodes200ResponseData.
        :rtype: List[TdNode]
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes: List[TdNode]):
        """Sets the nodes of this GetNodes200ResponseData.

        Result of the execution  # noqa: E501

        :param nodes: The nodes of this GetNodes200ResponseData.
        :type nodes: List[TdNode]
        """

        self._nodes = nodes
