from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.get_td_info200_response_data import GetTdInfo200ResponseData
from openapi_server import util

from openapi_server.models.get_td_info200_response_data import GetTdInfo200ResponseData  # noqa: E501

class GetTdInfo200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success=None, data=None, error=None):  # noqa: E501
        """GetTdInfo200Response - a model defined in OpenAPI

        :param success: The success of this GetTdInfo200Response.  # noqa: E501
        :type success: bool
        :param data: The data of this GetTdInfo200Response.  # noqa: E501
        :type data: GetTdInfo200ResponseData
        :param error: The error of this GetTdInfo200Response.  # noqa: E501
        :type error: str
        """
        self.openapi_types = {
            'success': bool,
            'data': GetTdInfo200ResponseData,
            'error': str
        }

        self.attribute_map = {
            'success': 'success',
            'data': 'data',
            'error': 'error'
        }

        self._success = success
        self._data = data
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'GetTdInfo200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_td_info_200_response of this GetTdInfo200Response.  # noqa: E501
        :rtype: GetTdInfo200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self) -> bool:
        """Gets the success of this GetTdInfo200Response.

        Whether the operation was successful  # noqa: E501

        :return: The success of this GetTdInfo200Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success: bool):
        """Sets the success of this GetTdInfo200Response.

        Whether the operation was successful  # noqa: E501

        :param success: The success of this GetTdInfo200Response.
        :type success: bool
        """
        if success is None:
            raise ValueError("Invalid value for `success`, must not be `None`")  # noqa: E501

        self._success = success

    @property
    def data(self) -> GetTdInfo200ResponseData:
        """Gets the data of this GetTdInfo200Response.


        :return: The data of this GetTdInfo200Response.
        :rtype: GetTdInfo200ResponseData
        """
        return self._data

    @data.setter
    def data(self, data: GetTdInfo200ResponseData):
        """Sets the data of this GetTdInfo200Response.


        :param data: The data of this GetTdInfo200Response.
        :type data: GetTdInfo200ResponseData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def error(self) -> str:
        """Gets the error of this GetTdInfo200Response.

        Error message if the operation was not successful  # noqa: E501

        :return: The error of this GetTdInfo200Response.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this GetTdInfo200Response.

        Error message if the operation was not successful  # noqa: E501

        :param error: The error of this GetTdInfo200Response.
        :type error: str
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error
