from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TdNodeFamilyType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    COMP = 'COMP'
    CHOP = 'CHOP'
    TOP = 'TOP'
    SOP = 'SOP'
    DAT = 'DAT'
    MAT = 'MAT'
    CUSTOM = 'CUSTOM'
    def __init__(self):  # noqa: E501
        """TdNodeFamilyType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TdNodeFamilyType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TdNodeFamilyType of this TdNodeFamilyType.  # noqa: E501
        :rtype: TdNodeFamilyType
        """
        return util.deserialize_model(dikt, cls)
