from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TdPythonMethodInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, signature=None, description=None):  # noqa: E501
        """TdPythonMethodInfo - a model defined in OpenAPI

        :param name: The name of this TdPythonMethodInfo.  # noqa: E501
        :type name: str
        :param signature: The signature of this TdPythonMethodInfo.  # noqa: E501
        :type signature: str
        :param description: The description of this TdPythonMethodInfo.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'name': str,
            'signature': str,
            'description': str
        }

        self.attribute_map = {
            'name': 'name',
            'signature': 'signature',
            'description': 'description'
        }

        self._name = name
        self._signature = signature
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'TdPythonMethodInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TdPythonMethodInfo of this TdPythonMethodInfo.  # noqa: E501
        :rtype: TdPythonMethodInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this TdPythonMethodInfo.

        Method name  # noqa: E501

        :return: The name of this TdPythonMethodInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TdPythonMethodInfo.

        Method name  # noqa: E501

        :param name: The name of this TdPythonMethodInfo.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def signature(self) -> str:
        """Gets the signature of this TdPythonMethodInfo.

        Method signature including parameters  # noqa: E501

        :return: The signature of this TdPythonMethodInfo.
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature: str):
        """Sets the signature of this TdPythonMethodInfo.

        Method signature including parameters  # noqa: E501

        :param signature: The signature of this TdPythonMethodInfo.
        :type signature: str
        """

        self._signature = signature

    @property
    def description(self) -> str:
        """Gets the description of this TdPythonMethodInfo.

        Description of the method  # noqa: E501

        :return: The description of this TdPythonMethodInfo.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TdPythonMethodInfo.

        Description of the method  # noqa: E501

        :param description: The description of this TdPythonMethodInfo.
        :type description: str
        """

        self._description = description
