from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TdPythonPropertyInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, type=None, value=None):  # noqa: E501
        """TdPythonPropertyInfo - a model defined in OpenAPI

        :param name: The name of this TdPythonPropertyInfo.  # noqa: E501
        :type name: str
        :param type: The type of this TdPythonPropertyInfo.  # noqa: E501
        :type type: str
        :param value: The value of this TdPythonPropertyInfo.  # noqa: E501
        :type value: object
        """
        self.openapi_types = {
            'name': str,
            'type': str,
            'value': object
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'value': 'value'
        }

        self._name = name
        self._type = type
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'TdPythonPropertyInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TdPythonPropertyInfo of this TdPythonPropertyInfo.  # noqa: E501
        :rtype: TdPythonPropertyInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this TdPythonPropertyInfo.

        Property name  # noqa: E501

        :return: The name of this TdPythonPropertyInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TdPythonPropertyInfo.

        Property name  # noqa: E501

        :param name: The name of this TdPythonPropertyInfo.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this TdPythonPropertyInfo.

        Type of the property  # noqa: E501

        :return: The type of this TdPythonPropertyInfo.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this TdPythonPropertyInfo.

        Type of the property  # noqa: E501

        :param type: The type of this TdPythonPropertyInfo.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def value(self) -> object:
        """Gets the value of this TdPythonPropertyInfo.

        Current value of the property (if serializable)  # noqa: E501

        :return: The value of this TdPythonPropertyInfo.
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value: object):
        """Sets the value of this TdPythonPropertyInfo.

        Current value of the property (if serializable)  # noqa: E501

        :param value: The value of this TdPythonPropertyInfo.
        :type value: object
        """

        self._value = value
