from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TdPythonClassInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, type=None, description=None):  # noqa: E501
        """TdPythonClassInfo - a model defined in OpenAPI

        :param name: The name of this TdPythonClassInfo.  # noqa: E501
        :type name: str
        :param type: The type of this TdPythonClassInfo.  # noqa: E501
        :type type: str
        :param description: The description of this TdPythonClassInfo.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'name': str,
            'type': str,
            'description': str
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'description': 'description'
        }

        self._name = name
        self._type = type
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'TdPythonClassInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TdPythonClassInfo of this TdPythonClassInfo.  # noqa: E501
        :rtype: TdPythonClassInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this TdPythonClassInfo.

        Name of the class or module  # noqa: E501

        :return: The name of this TdPythonClassInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this TdPythonClassInfo.

        Name of the class or module  # noqa: E501

        :param name: The name of this TdPythonClassInfo.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this TdPythonClassInfo.

        Type of the Python entity  # noqa: E501

        :return: The type of this TdPythonClassInfo.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this TdPythonClassInfo.

        Type of the Python entity  # noqa: E501

        :param type: The type of this TdPythonClassInfo.
        :type type: str
        """
        allowed_values = ["class", "module", "function", "object"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def description(self) -> str:
        """Gets the description of this TdPythonClassInfo.

        Description of the class or module  # noqa: E501

        :return: The description of this TdPythonClassInfo.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TdPythonClassInfo.

        Description of the class or module  # noqa: E501

        :param description: The description of this TdPythonClassInfo.
        :type description: str
        """

        self._description = description
