from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UpdateNodeRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, node_path=None, properties=None):  # noqa: E501
        """UpdateNodeRequest - a model defined in OpenAPI

        :param node_path: The node_path of this UpdateNodeRequest.  # noqa: E501
        :type node_path: str
        :param properties: The properties of this UpdateNodeRequest.  # noqa: E501
        :type properties: Dict[str, object]
        """
        self.openapi_types = {
            'node_path': str,
            'properties': Dict[str, object]
        }

        self.attribute_map = {
            'node_path': 'nodePath',
            'properties': 'properties'
        }

        self._node_path = node_path
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateNodeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The update_node_request of this UpdateNodeRequest.  # noqa: E501
        :rtype: UpdateNodeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node_path(self) -> str:
        """Gets the node_path of this UpdateNodeRequest.

        Path to the node (e.g., /project1/null1)  # noqa: E501

        :return: The node_path of this UpdateNodeRequest.
        :rtype: str
        """
        return self._node_path

    @node_path.setter
    def node_path(self, node_path: str):
        """Sets the node_path of this UpdateNodeRequest.

        Path to the node (e.g., /project1/null1)  # noqa: E501

        :param node_path: The node_path of this UpdateNodeRequest.
        :type node_path: str
        """
        if node_path is None:
            raise ValueError("Invalid value for `node_path`, must not be `None`")  # noqa: E501

        self._node_path = node_path

    @property
    def properties(self) -> Dict[str, object]:
        """Gets the properties of this UpdateNodeRequest.


        :return: The properties of this UpdateNodeRequest.
        :rtype: Dict[str, object]
        """
        return self._properties

    @properties.setter
    def properties(self, properties: Dict[str, object]):
        """Sets the properties of this UpdateNodeRequest.


        :param properties: The properties of this UpdateNodeRequest.
        :type properties: Dict[str, object]
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties
