from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.update_node200_response_data_failed_inner import UpdateNode200ResponseDataFailedInner
from openapi_server import util

from openapi_server.models.update_node200_response_data_failed_inner import UpdateNode200ResponseDataFailedInner  # noqa: E501

class UpdateNode200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, path=None, updated=None, failed=None, message=None):  # noqa: E501
        """UpdateNode200ResponseData - a model defined in OpenAPI

        :param path: The path of this UpdateNode200ResponseData.  # noqa: E501
        :type path: str
        :param updated: The updated of this UpdateNode200ResponseData.  # noqa: E501
        :type updated: List[str]
        :param failed: The failed of this UpdateNode200ResponseData.  # noqa: E501
        :type failed: List[UpdateNode200ResponseDataFailedInner]
        :param message: The message of this UpdateNode200ResponseData.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'path': str,
            'updated': List[str],
            'failed': List[UpdateNode200ResponseDataFailedInner],
            'message': str
        }

        self.attribute_map = {
            'path': 'path',
            'updated': 'updated',
            'failed': 'failed',
            'message': 'message'
        }

        self._path = path
        self._updated = updated
        self._failed = failed
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateNode200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The update_node_200_response_data of this UpdateNode200ResponseData.  # noqa: E501
        :rtype: UpdateNode200ResponseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self) -> str:
        """Gets the path of this UpdateNode200ResponseData.

        Path of the node that was updated  # noqa: E501

        :return: The path of this UpdateNode200ResponseData.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this UpdateNode200ResponseData.

        Path of the node that was updated  # noqa: E501

        :param path: The path of this UpdateNode200ResponseData.
        :type path: str
        """

        self._path = path

    @property
    def updated(self) -> List[str]:
        """Gets the updated of this UpdateNode200ResponseData.

        List of property names that were successfully updated  # noqa: E501

        :return: The updated of this UpdateNode200ResponseData.
        :rtype: List[str]
        """
        return self._updated

    @updated.setter
    def updated(self, updated: List[str]):
        """Sets the updated of this UpdateNode200ResponseData.

        List of property names that were successfully updated  # noqa: E501

        :param updated: The updated of this UpdateNode200ResponseData.
        :type updated: List[str]
        """

        self._updated = updated

    @property
    def failed(self) -> List[UpdateNode200ResponseDataFailedInner]:
        """Gets the failed of this UpdateNode200ResponseData.

        List of properties that failed to update  # noqa: E501

        :return: The failed of this UpdateNode200ResponseData.
        :rtype: List[UpdateNode200ResponseDataFailedInner]
        """
        return self._failed

    @failed.setter
    def failed(self, failed: List[UpdateNode200ResponseDataFailedInner]):
        """Sets the failed of this UpdateNode200ResponseData.

        List of properties that failed to update  # noqa: E501

        :param failed: The failed of this UpdateNode200ResponseData.
        :type failed: List[UpdateNode200ResponseDataFailedInner]
        """

        self._failed = failed

    @property
    def message(self) -> str:
        """Gets the message of this UpdateNode200ResponseData.

        Summary message about the update operation  # noqa: E501

        :return: The message of this UpdateNode200ResponseData.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this UpdateNode200ResponseData.

        Summary message about the update operation  # noqa: E501

        :param message: The message of this UpdateNode200ResponseData.
        :type message: str
        """

        self._message = message
