from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UpdateNode200ResponseDataFailedInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, reason=None):  # noqa: E501
        """UpdateNode200ResponseDataFailedInner - a model defined in OpenAPI

        :param name: The name of this UpdateNode200ResponseDataFailedInner.  # noqa: E501
        :type name: str
        :param reason: The reason of this UpdateNode200ResponseDataFailedInner.  # noqa: E501
        :type reason: str
        """
        self.openapi_types = {
            'name': str,
            'reason': str
        }

        self.attribute_map = {
            'name': 'name',
            'reason': 'reason'
        }

        self._name = name
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateNode200ResponseDataFailedInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The update_node_200_response_data_failed_inner of this UpdateNode200ResponseDataFailedInner.  # noqa: E501
        :rtype: UpdateNode200ResponseDataFailedInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this UpdateNode200ResponseDataFailedInner.

        Name of the property that failed to update  # noqa: E501

        :return: The name of this UpdateNode200ResponseDataFailedInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UpdateNode200ResponseDataFailedInner.

        Name of the property that failed to update  # noqa: E501

        :param name: The name of this UpdateNode200ResponseDataFailedInner.
        :type name: str
        """

        self._name = name

    @property
    def reason(self) -> str:
        """Gets the reason of this UpdateNode200ResponseDataFailedInner.

        Reason for the failure  # noqa: E501

        :return: The reason of this UpdateNode200ResponseDataFailedInner.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this UpdateNode200ResponseDataFailedInner.

        Reason for the failure  # noqa: E501

        :param reason: The reason of this UpdateNode200ResponseDataFailedInner.
        :type reason: str
        """

        self._reason = reason
